version: '2'
services:
  consumerSlow:
    image: local/training-stream:1.0-SNAPSHOT
    environment:
      JAVA_TOOL_OPTIONS: -Dconsumer.group=slowGroup -Dapp.type=consumer -Dwork.duration.ms=2000 -Dlog.type=kafka -Dkafka.bootstrap.servers=kafka:9092
    networks:
      - kafka_default
networks:
  kafka_default:
     external: true
