version: '2'
services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: zookeeper:3.5.5
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    container_name: kafka
    hostname: kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 10
      KAFKA_OFFSETS_RETENTION_MINUTES: 20160
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 4
  kafkahq:
    image: tchiotludo/kafkahq:0.9.0
    container_name: kafkahq
    hostname: kafkahq
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:kafkahq.docker.localhost"
    depends_on:
      - kafka
    volumes:
      - ./kafkahq/kafkahq.yml:/app/application.yml:ro
  traefik:
    image: traefik:maroilles-alpine
    container_name: traefik
    command: --api --docker
    ports:
      - 80:80
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.docker.localhost"
    depends_on:
      - kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
