version: '2'
services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: zookeeper:3.5.5
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    container_name: kafka
    hostname: kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 10
      KAFKA_OFFSETS_RETENTION_MINUTES: 20160
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 4
  kafkahq:
    image: tchiotludo/kafkahq:latest
    container_name: kafkahq
    hostname: kafkahq
    ports:
    - 8080:8080
    depends_on:
      - kafka
    volumes:
      - ./kafkahq/kafkahq.conf:/app/application.conf:ro

